### ISSUE TITLE
No way to "Undeploy" a Command component to an endpoint

### ISSUE THREAD

**Issue by dannycohen** [Particular/ServiceMatrix#159]
1. If I have mistakenly deployed a component to an endpoint, I need to delete that component
* If the component is a Command Sender or Command Processor - I need to manually delete both components and the command message, and re-create them, otherwise I'll be left with a command without sender, processor, or both.
* So we either need:
   1. An "Undeploy" command component from an endpoint
   * A "Delete" command component that is smart enough to delete the other command Components and the command message itself (similar to the delete of a command asking for permission to delete the components as well as the command)

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
