### ISSUE TITLE
Design & organize Icons in SM toolbar

### ISSUE THREAD

**Issue by dannycohen** [Particular/ServiceMatrix#190]
1. Current icon order is not optimal (mixes help, views, register etc. See image below)
* Visual language for icons should also be aligned 

![image](https://f.cloud.github.com/assets/3889023/1971760/e5b5dcec-8337-11e3-8e61-06b5c9c9e495.png)

// CC @esculli 

Thoughts ?

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
