### ISSUE TITLE
Add Status indications to status bar during code generation / configuration activities

### ISSUE THREAD

**Issue by dannycohen** [Particular/ServiceMatrix#204]
#### Current status

When performing operations - especially when SM / VS has just started - the operations take a long time to complete, during which the cursor is set to an hourglass and there is not status indication text in the VS status bar 

#### Requested Change

1. Add Status text during operations to notify the user of activity progress
* Specific activities include 
   * creation of endpoint, service, deployment etc.
   * downloading and completion of downloading of Nuget packages 
      * (include the Nuget package name in the status text) 
* Make sure to clear status on completion and if an exception occurs

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
