### ISSUE TITLE
Use interfaces instead of classes for Events generated by ServiceMatrix

### ISSUE THREAD

**Issue by jdrat2000** [Particular/ServiceMatrix#220]
@dannycohen 

Noticed that when events are created by ServiceMatrix the code generator doesn't create interfaces and then publish messages based on the interfaces.  Interfaces would perhaps be more consistent with the best practices of NSB.

Curious as to the direction on message/contract definition in general.   I am rusty but seem to recall some tools (biztalk, vitria, tibco) have a focus on contract and message definition.    I love the way NSB messages are just Poco's so I am a bit conflicted as to how far I'd wish it to be taken in this tool.   The class building capabilities of Visual Studio might suffice..

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
