### ISSUE TITLE
Allow users select Container

### ISSUE THREAD

**Issue by esculli** [Particular/ServiceMatrix#226]
Add Property "Container" at solution level

When property changed:
- Add nuget references to container  nuget packages
- In EndpointConfig.cs file, implement IWantCustomInitialization and in the Init method -> Configure.With(); GlobalContainer.GlobalSetup();
- On the Code/Infrastructure project, generate the static class GlobalContainer, with the following members:
* GlobalContainer.Setup()
* GlobalContainer.SystemWideContainerSetup()
* GlobalContainer.Instance property (IContainer)
- Add link on each endpoint project to the GlobalContainer file
- Generate EndpointSpecificContainerSetup file on each endpoint, so container can be configured individually
- On canvas, add menu "Configure Container" to open EndpointSpecificContainerSetup file from endpoint

@udidahan, @andreasohlund, @dannycohen feel free to provide more details on this.

@andreasohlund can you provide the full list of container that we should support?

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
