### ISSUE TITLE
Global option for combining config files

### ISSUE THREAD

**Issue by fafachd** [Particular/ServiceMatrix#257]
ServiceMatrix currently generates 6 different configuration files for every endpoint and puts them multiple levels deep in solution folders (GeneratedCode/Config). IMO, it is much less cumbersome for an endpoint to have a single app.config (web.config, etc.) showing all settings at a glance. Since the is a matter of preference: 

I recommend adding a global "CombineConfig" setting that lets a user specify whether they want config files combined or split apart.

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
