### ISSUE TITLE
The generated Logging.config gets added in the wrong location

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceMatrix#259]
All of the generated config, gets created under a `Config` folder under `Generated Code`.
However, `Logging.config` gets created at the root level. 

Shouldn't this be also under config?
![image](https://f.cloud.github.com/assets/854553/2380321/a23c3f56-a8a8-11e3-85cf-0a6cf9e64a75.png)

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
