### ISSUE TITLE
Redundant interfaces are being generated for MessageHandlers

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceMatrix#260]
When creating a message handler, the code generated has a redundant interface and a component called NServiceBus.INServiceBusComponent.  I believe removing both these interfaces from the generated code will make it much better.  When we write regular NServiceBus code, we don't do this. We shouldn't be auto-genning un-necessary code. 
 
The following empty interface is defined under `Infrastructure` and it seems to get added to every NServiceBus component, i.e. Handlers, Sagas etc. Why is this necessary? Its also defined under the NServiceBus namespace which is incorrect, as this interface belongs to the Sample solution and not NServiceBus. 
```c#
namespace NServiceBus
{
    public interface INServiceBusComponent
    {
    }
}
```

````c#
 public partial class SubmitOrderProcessor : ISubmitOrderProcessor, NServiceBus.INServiceBusComponent, IHandleMessages<SubmitOrder>
    {
		
		public void Handle(SubmitOrder message)
		{
			// Handle message on partial class
			this.HandleImplementation(message);
		}

		partial void HandleImplementation(SubmitOrder message);

        public IBus Bus { get; set; }

    }
    
    public partial interface ISubmitOrderProcessor
    {
		
    }
````

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
