### ISSUE TITLE
Make the Show Canvas button more accessible

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceMatrix#268]
Currently if we close the Solution Explorer, Guidance window, etc and we have the solution that ServiceMatrix has generated, there is currently no way for the user to know how to get to the canvas display if the user had closed it.

Integrate the Show Canvas button within Visual Studio so it would be easy for the user to get to the canvas view. 

cc/ @udidahan @dannycohen

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
