### ISSUE TITLE
Problem deploying a component to an existing endpoint

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceMatrix#289]
**Steps to reproduce**
1. Create an ASP.NET MVC Endpoint (FE) which sends a SubmitOrder command
2. Deploy the SubmitOrderProcessor to a new NSB endpoint called BE1
3. Send a command called RequestApproval from the SubmitOrderProcessor
4. Deploy the RequestApprovalProcessor to a new NSB endpont called BE2
5. Make the processor reply with a message and accept the saga recommendation
6. Publish a new event called OrderAccepted
7. Click on teh OrderAccepted and add subscriber for the event and add new subscribers called Billing and Shipping. At this point the canvas looks correct which is as follows:
![image](https://cloud.githubusercontent.com/assets/854553/2627702/909003a0-be10-11e3-9496-75c550395dd9.png)
8. Now, Deploy the Billing processor to BE1 and the shipping processor to BE2. Notice that the BE2 does not have the handler component!
![image](https://cloud.githubusercontent.com/assets/854553/2627712/c5ddbf48-be10-11e3-9cb7-302d423b5db0.png)

**NOTE** 
Closing and reopening the canvas did not help.
I had to close Visual Studio and reopen the solution for the canvas to be correct.

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
