### ISSUE TITLE
Implement the  User code changes prompt assistance for new Handlers 

### ISSUE THREAD

**Issue by jdrat2000** [Particular/ServiceMatrix#290]
User code changes required is prompted for new publishers/senders but not when new handlers are needed.  

For example: When new outbound messages are added to a component after the initial build and code generation the prompt for 'User Code Changes Required' expresses the opportunity to add the publish/send code and provides the code in the pop up. 

When adding a new event subscription to a saga could we provide a 'User code changes required' dialog  like we do for senders/publishers but instead offer the code implementing the handler partial method HandleImplementation(XXXX) in the same way as shown below:

```C#
 partial void HandleImplementation(OrderAccepted message)
 {
 // TODO: OrderAcceptedProcessor: Add code to handle the OrderAccepted message.
            Console.WriteLine("Billing received " + message.GetType().Name);
}
```

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
