### ISSUE TITLE
ServiceMatrix generating the Send api code in the autogenerated code rather than user code

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceMatrix#292]
**Steps to Repro**
1. Create an ASP.NET MVC endpoint and make it send a SubmitOrder command and deploy the component.
2. Inspect the code. The send seems to be in the auto generated section rather than the partial class generated for the user.

Same reasons apply why we want to move this to user generated code like we did for Bus.Publish.
If the user has a condition around which they need to do a Send, it is not currently possible with the Send being in the autogenerated class.

```c#
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by ServiceMatrix.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using NServiceBus;
using Application7.InternalMessages.Commands.Sales;

namespace Application7.Sales
{
    public partial class SubmitOrderSender : ISubmitOrderSender, ServiceMatrix.Shared.INServiceBusComponent
    {
        public void Send(SubmitOrder message)
        {
            ConfigureSubmitOrder(message);
            Bus.Send(message);
        }

        partial void ConfigureSubmitOrder(SubmitOrder message);

        public IBus Bus { get; set; }

    }

	
    public partial interface ISubmitOrderSender
    {
        void Send(SubmitOrder message);
    }
}
```

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
