### ISSUE TITLE
Renaming components from the canvas not very intuitive

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceMatrix#306]
When attempting to rename a component on the canvas:

It opens the rename in teh SolutionBuilder, however the node being renamed is out of view, giving the impression to the user that the rename is not working. In the meanwhile, if you have SolutionBuilder, you need to scroll to find the component, where the cursor is set for rename on the component

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
