### ISSUE TITLE
Confusing properties

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceMatrix#314]
![image](https://cloud.githubusercontent.com/assets/122651/2691891/94d1b262-c390-11e3-860e-cff79d35595f.png)

The properties in blue look the same.

The one in red is now called Maximum Concurrency Level

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
