### ISSUE TITLE
Add component to Send command code view

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceMatrix#315]
If I add a component that Sends a command
And then I click on View Code, I end-up in something like:
```c#
public partial class ShoeSender
{
		
}
```

What am I suppose to do here?

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
