### ISSUE TITLE
Update ServiceMatrix version to be automatically updated

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceMatrix#319]
Currently the file `ServiceMatrixVersion.txt` that's under the solution items displays the version of ServiceMatrix used.
This needs to be automatically updated using gitflow version instead.

![image](https://cloud.githubusercontent.com/assets/854553/2699516/8a7229c4-c407-11e3-80af-d02f4dc365f8.png)

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
