### ISSUE TITLE
Remove default connectionstring for Azure ServiceBus transport

### ISSUE THREAD

**Issue by yvesgoeleven** [Particular/ServiceMatrix#329]
When selecting the azure servicebus transport, it defaults the connectionstring to 'UseDevelopmentStorage=true', but that only makes sense for storage queues, there is no default for servicebus, so please remove the default value as it makes no sense

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
