### ISSUE TITLE
Use Visual Studio extension for class name renaming

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceMatrix#331]
For the code refactor for renaming components and classes:
- use what's available from Visual Studio. See: http://msdn.microsoft.com/en-us/library/envdte80.codeelement2.renamesymbol(v=vs.110).aspx
- Remove dependency on https://github.com/esculli/NRefactory-Samples

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
