### ISSUE TITLE
Related Property exception when building the solution

### ISSUE THREAD

**Issue by jdrat2000** [Particular/ServiceMatrix#333]
Not every time but occasionally I get an exception building.  The build completes OK and is runnable but the exception list contains the error below. 

Indeed if I go to this property and simply erase it all is well... 

```
Error 1 'OnlineSales' has a link in its 'Related Items' property ('ServiceMatrix Guidance') to a guidance workflow in the solution that could not be found. You must update the 'Related Item' of type 'Guidance Link' to reference an existing guidance workflow.
```

**Comment by agilmore30** [comment]
Hi

I have the same problem. I get this error every time I build any project within a solution. It doesn't actually affect the build, but it is annoying. In a similar way to above, I excluded all bin and obj libraries from my svn check-in. I'm not sure if this is related, but the error only started to occur after this. 

Thanks - Adam.

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
