### ISSUE TITLE
Add Nuget as a package reference for the VSIX file.

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceMatrix#345]
When installing ServiceMatrix and VS has an older version of Nuget Package Manager console, then creating a new Application fails when trying to download the latest version of `NServiceBus.Interfaces`
Right now, ServiceMatrix, only installs Nupattern tool kit as a reference. It also needs to include Nuget Package Manager as a reference.

**Steps to Repro**
1. Launch any Hands on Labs VM 
2. Download the latest version of Service Matrix
3. Create a new solution.
4. Notice the failure

**Workaround**
Install the latest version of Nuget Package Manager. And after that SM is able to create solutions properly.

Since we depend on Nuget, we must explicitly add that as a reference to the VSIX.

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
