### ISSUE TITLE
Provide the ability to deploy multiple components from a service together

### ISSUE THREAD

**Issue by fsimonazzi** [Particular/ServiceMatrix#363]
When you have undeployed components in a service you need to deploy them one at a time. It would be good to be able to choose several components to deploy to the same endpoint.

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
