### ISSUE TITLE
No validation for unique name when renaming a component

### ISSUE THREAD

**Issue by fsimonazzi** [Particular/ServiceMatrix#364]
You cannot create a component with the same name as an existing component, but you can rename a component with the same the name of another component in the same service.

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
