### ISSUE TITLE
Rename Services

### ISSUE THREAD

**Issue by Romiko** [Particular/ServiceMatrix#374]
If I rename a service, under services. It will not fix all namespaces in the Internal project where commands, events and messages are.

To reproduce, rename a service, then go look at the commands in Internal, the namespace is still the old one.

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
