### ISSUE TITLE
When license is expired and when opening a SM solution, add ability to enter new license

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceMatrix#380]
Currently when the license has expired and user opens an existing SM solution, in addition to displaying an expiration message add an option that will allow the user to enter the new license.

--
**Current Behavior:**
When license is expired and user opens an existing solution, first a license expiration dialog is displayed:
![image](https://cloud.githubusercontent.com/assets/854553/3331386/56dcf5fe-f7dc-11e3-8a54-b2973d6d3cdc.png)
If the user closes the dialog, without entering the license, then the canvas is displayed in a read only mode with an expiration message.
![image](https://cloud.githubusercontent.com/assets/854553/3331349/d5d44b10-f7db-11e3-889f-769a849aa570.png)
NOTE: When license is expired, users will not be allowed to create new solutions using SM.

**Proposed**
- Add a button in addition to the expiration message in teh canvas, where the user can enter the license.
- Remove the toolbar license button, which at the moment does nothing if the license is valid.

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
