### ISSUE TITLE
Component code is generated to hard-coded paths based on conventions

### ISSUE THREAD

**Issue by fsimonazzi** [Particular/ServiceMatrix#384]
NuPattern generates projects and files using the specified values, but it keeps a reference to the generated code to account for renames (the "reference links").

In order to make this work, NuPattern requires a specific syntax when specifying a target path, with tokens that cause the unfold logic to traverse the reference links.

There is code in ServiceMatrix for specifying the target path for component code on the deployed components that duplicates the name of the name for the projects generated for an endpoint instead of relaying on NuPattern to figure out the target project. This causes a disconnect if the endpoint project is renamed.

Code for endpoint code generation:
```c#
                if (endpoint != null)
                {
                    var path = String.Format ("\\{0}.{1}", app.InstanceName, endpoint.InstanceName);
                    if (this.AddInfrastructureFolder)
                    {
                        path += "\\Infrastructure";                        
                    }

                    path += String.Format("\\{0}", component.Parent.Parent.CodeIdentifier);
                    return path;
                }
```

Configuration for the project name:

```
{Root.InstanceName}.{InstanceName}
```

To repro this issue:
1. Create a new app. 
2. Add an endpoint.
3. Send a command from the endpoint.
4. Build. It will fail because the handler is not deployed, but the sender code will be generated on the endpoint.
5. Rename the endpoint project.
6. Send a new command from the endpoint.
7. Build. It will create the handler code on a new solution folder with the same name the endpoint project used to have.

Additionally, the component code generation is originated from the Component element, when it should probably be generated from ComponentLink elements, which represent a component that is actually deployed. This will become a more pressing issue when endpoints can target different versions of NSB.

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
