### ISSUE TITLE
When publishing an event or sending a command from either a saga or a component that handles multiple messages, the publish/send code gets added to all handlers, when code is generated for the first time.

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceMatrix#391]
**Steps to Reproduce**
- Create an use case for Saga Correlation (using events). In this case, Shipping endpoint handles both OrderReceived and OrderBilled and is a saga
![image](https://cloud.githubusercontent.com/assets/854553/3706467/d21eeb50-1429-11e4-926c-d2685e3852e9.png)

- Make this publish an event, `OrderShipped`
- In the code, both event handlers have teh publish code. 

```c#
 public partial class OrderBilledHandler
    {
		
        partial void HandleImplementation(OrderBilled message)
        {
            // TODO: OrderBilledHandler: Add code to handle the OrderBilled message.
            Console.WriteLine("Shipping received " + message.GetType().Name);

            var orderShipped = new Application8.Contracts.Shipping.OrderShipped();
            Bus.Publish(orderShipped);
        }

        partial void HandleImplementation(OrderReceived message)
        {
            // TODO: OrderBilledHandler: Add code to handle the OrderReceived message.
            Console.WriteLine("Shipping received " + message.GetType().Name);

            var orderShipped = new Application8.Contracts.Shipping.OrderShipped();
            Bus.Publish(orderShipped);
        }
    }
```

NOTE: The same issue applies for the Send as well. 

**Proposed Fix**
Since there are multiple handlers involved, SM should not automatically add the publish code or send code to all handlers. It should just offer the code for the user to add it where they choose even if the file has not been generated yet.
For example:
![image](https://cloud.githubusercontent.com/assets/854553/3706547/a2732e9c-142a-11e4-9806-879f65179db9.png)

The wording of the message in teh dialog could be more appropriate like:
`ServiceMatrix has detected multiple handlers in this component. Please add the following code to the appropriate handler`
@udidahan @dannycohen - Your thoughts on this?

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
