### ISSUE TITLE
When sending a command from the same sender in a MVCEndpoint, prompts user instead of autogenerating the code

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceMatrix#402]
**Steps to repro:**
1. Generate a ASP.NET MVC endpoint that sends a command called `SubmitOrder` in `Sales`
2. Deploy the handler to a new NSB Endpoint and build the solution
3. From the `SubmitOrderSender` in the MVC endpoint, send a new command called, `CancelOrder`

It should automatically generate the Sender code since its autogenerated code. Instead it prompts the user.

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
