### ISSUE TITLE
Moving any of the projects created by ServiceMatrix to Solution Folder results in creating a error when pressing "View Code" on handler.

### ISSUE THREAD

**Issue by eiki25** [Particular/ServiceMatrix#406]
Steps to repro:
1. Create a new endpoint in ServiceMatrix (optional)
2. Add new/existing service as a subscriber to any existing event
3. Deploy the handler to the new/existing endpoint
3. Create a Solution folder and move the project containing the endpoint the solution folder.
4. Click the handler and press view code.

Error:Object reference not set to an instance of an object.

Service Matrix Version: 2.1.2

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
