### ISSUE TITLE
Have an option to turn off the auto generation of the TestController code for MVC endpoints 

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceMatrix#407]
When creating a new MVC Endpoint, ServiceMatrix automatically generates the test controller and test view code. While it may be useful during early development, at some point the test controllers may not be needed and we should be able to turn off autogeneration for this.
Have an option to disable this generation at an endpoint level.

Relates to https://github.com/Particular/Requirements/issues/112

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
