### ISSUE TITLE
SolutionBuilder and the canvas can get out of sync with link removal

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceMatrix#418]
SolutionBuilder has a context menu on links that allows their deletion,  the canvas has no such option.
When a link is removed it is still show on the canvas.  Code generation acts as though the link is missing (which is correct).

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
