### ISSUE TITLE
Generated SignalR Hub should be a partial class

### ISSUE THREAD

**Issue by dprothero** [Particular/ServiceMatrix#422]
Developers will likely want to be able to add methods for their web client to be able to call into to their SignalR Hub. Right now, the "SignalRHubsFor<MessageName>.cs" file is generated as a public class that can't be extended. I suggest this be made a partial class so that it can be extended, much like what is done with the Handlers and Senders right now.

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
