### ISSUE TITLE
Cursor doesn't default to normal when prompting the user for code changes, instead shows the busy cursor

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceMatrix#423]
When ServiceMatrix prompts the user to modify the code, it shows the code to copy to clipboard, BUT the mouse pointer shows as BUSY, however you can still click the copy to clipboard button to finalise the process. 

![bug-mousepointerbusy](https://cloud.githubusercontent.com/assets/579058/3900516/85b3be84-228f-11e4-93a3-f0c92826bd28.png)

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
