### ISSUE TITLE
Add a new MVC5 Host and support for SignalR 2.x

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceMatrix#426]
At the moment, we only support MVC4 Endpoint. 
Add Support for MVC5

This will also involve adding SignalR v2 where relevant.

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
