### ISSUE TITLE
Allow restructuring of existing endpoints into solution folders

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceMatrix#427]
Allow restructuring of code into solution folders created by users. ServiceMatrix does not currently support this due to the existing design of how path is being provided for the generated files.

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
