### ISSUE TITLE
Design a better UX for the current ServiceMatrix dialogs

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceMatrix#428]
At the moment the dialog boxes are inconsistent, in some cases, extra dialogs are shown, etc.
Revisit the UX for all the dialog interactions and come up with a new dialog proposal / changes.

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
