### ISSUE TITLE
The test controller landing page is tightly coupled with particular.net branding and menus

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceMatrix#430]
At the moment, we have the test controller page design mirror closely with the actual particular.net website.
There is a bloat of css and also because it is tightly coupled, any time we change links or design on the particular.net website, SM test controller pages will have broken links.

**Proposal**
- Have a minimalistic design. 
- Keep the branding consistent but not the same as that of Particular.net

Relates to #350

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
