### ISSUE TITLE
Generated code is not consistently indented

### ISSUE THREAD

**Issue by dprothero** [Particular/ServiceMatrix#436]
The ServiceMatrix code generates code that is sometimes indented using spaces and other times indented with tabs. An example is WebGlobalInitialization.cs in an ASP.NET MVC project.

See [this issue](https://github.com/Particular/Operations.DocsWeb/issues/118) for how this was discovered.

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
