### ISSUE TITLE
Publishing an event from ASP.NET MVC endpoint creates empty "Sender" code

### ISSUE THREAD

**Issue by dprothero** [Particular/ServiceMatrix#438]
If you publish an event from an ASP.NET endpoint:
![servicematrix-publishevent](https://cloud.githubusercontent.com/assets/1897006/5238941/19f63ce0-7883-11e4-80f1-320f3770ef02.png)

It creates a Sender component (see BrowsedProductSender):
![servicematrix-pubsubcanvaswired](https://cloud.githubusercontent.com/assets/1897006/5238944/38d6b766-7883-11e4-97a5-4ba5c694cb22.png)

However, when you go to view the code for that component:
![servicematrix-browsedproductsender](https://cloud.githubusercontent.com/assets/1897006/5238946/4dda4e98-7883-11e4-9e98-75872f2b9994.png)

You are left with an empty method:

````C#
namespace OnlineSalesPubSub.Marketing
{
    public partial class BrowsedProductSender
    {
		
    }
}
````

It appears the `TestMessagesController` is publishing the event itself rather than using the Sender component:

````C#
[HttpPost]
public string SendMessageBrowsedProduct(BrowsedProduct BrowsedProduct)
{
    ConfigureBrowsedProduct(BrowsedProduct);
    MvcApplication.Bus.Publish(BrowsedProduct);
    return "<p> BrowsedProduct published</p>";
}
````

This seems confusing.

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
