### ISSUE TITLE
The ISender Component is not automatically registered in a NSB Host

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceMatrix#439]
**Steps to Repro**
1. Create a NSB Host Called SenderHost
2. Make the SenderHost send a new command called `SendSomeCommand`
3. Deploy the handler to another Host called ReceiverHost
4. Add a bootstrapper.cs in the SenderHost that uses the SenderComponent to send a message.
5. Notice that the sender component is null

**Workaround**
In the EndpointConfig.cs class add the registration for the sender component manually.

```c#
public partial class EndpointConfig    
    {
        public void Customize(BusConfiguration configuration)
        {
            // For production use, please select a durable persistence.
            // To use RavenDB, install-package NServiceBus.RavenDB and then use configuration.UsePersistence<RavenDBPersistence>();
            // To use SQLServer, install-package NServiceBus.NHibernate and then use configuration.UsePersistence<NHibernatePersistence>();
            if (Debugger.IsAttached)
            {
                configuration.UsePersistence<InMemoryPersistence>();
            }

            configuration.RegisterComponents(c => c.ConfigureComponent<SendSomeCommandSender>(DependencyLifecycle.SingleInstance));
        }
    }
```
 
If self hosting add the register component to the bus configuration object during the bus creation / startup.

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
