### ISSUE TITLE
If multiple endpoints send the same command and the handler does a reply, only the first endpoint receives the response.

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceMatrix#440]
It is possible for multiple endpoints to send the same command.
The command will be handled by the same command handler.
However, if the handler does a reply, the response is sent to only one of the Senders and not all of the Senders. 

**Workaround**:
Add the `IHandleMessages<ResponseMessage>` in the partial class of the Sender in the endpoint.

--

**Steps to reproduce**
![screen shot 2015-02-06 at 11 46 24 am](https://cloud.githubusercontent.com/assets/854553/6086444/88e0118c-adf6-11e4-9309-c5f412429e20.png)

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.
