### ISSUE TITLE
Should we use poor Service Matrix at all?

### ISSUE THREAD

**Issue by boudinov** [Particular/ServiceMatrix#446]
Hello,

Using VS2013 Update5, i can hardly work for 5 minutes in Service Matrix, without getting something broken in the project and/or builder or canvas, got multiple VS crashes too. Same happens on different PCs,
The idea of this product is really nice, but the implementation seems so incomplete and useless, and kind of retired?

The first functional limitation, is that we cannot send command from one service to the other. Which makes it impossible to design a Process Manager (using NSB saga), which receives events and sends commands only, and resides in it's own service(bounded context). Correct?

Do you plan to do any fixes and improvements for this product?

Thanks

**Comment by indualagarsamy** [comment]
@boudinov - Thank you for raising this. ServiceMatrix shouldn't crash in the manner you are describing. Although there has been known issues around when the generated endpoint locations are changed, for example using Solution Folders. 

From a SOA perspective, services don't send commands to other services. 
However, you can have endpoints that can send commands that belong to the same service boundary to other endpoints. Are you having trouble using it as the documentation describes here: http://docs.particular.net/servicematrix/getting-started-sagasfullduplex-2.0

As far as any planned improvements or new features, we aren't planning to add new features at this moment. 
We try and tell our users that ServiceMatrix is a prototyping tool and is not meant for production. As you rightly mention, this is a very difficult space to begin with and at the time we built this tool, we used NuPattern to build the VS extension which is no longer supported for VS2015 and that's something that's being discussed internally. 

ServiceMatrix is a capability that offers the user, especially a new user, the promise of setting up the messaging flow in a easy way without the hassles of knowing how to route messages. That fundamental capability is being looked at from a platform as a whole and that's something that will be addressed in our platform. It may not exactly manifest itself as a feature in ServiceMatrix, but perhaps something that will touch the whole Particular Platform and again these are being discussed.  We are still committed to our original vision of what ServiceMatrix was trying to accomplish. 

Does this answer your question?

**Comment by boudinov** [comment]
Hello and thanks for the answer. Exactly what i was looking for;)
