### ISSUE TITLE
Service Matrix Visual Studio 2015 and Community version

### ISSUE THREAD

**Issue by patagoniahiker** [Particular/ServiceMatrix#447]
Hello, are you planning to update Service Matrix for Visual Studio 2015 developers.

**Comment by SimonCropp** [comment]
ServiceMatrix has been discontinued. Please see the [ServiceMatrix product page](http://www.particular.net/servicematrix) for more information.

Please [contact us](http://particular.net/contactus) if you would like discuss this further.

**Comment by patagoniahiker** [comment]
This is sad, since the developer community found it easier to use the Service Matrix to jump start work

**Comment by richardrooks** [comment]
over a year later now...any update?
